# Generated by Django 5.1.15 on 2026-09-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_activityevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterresource',
            name='resource_type',
            field=models.CharField(choices=[('video', 'Video (MP4)'), ('notes', 'Notes (PDF)'), ('textbook', 'Textbook Excerpt (PDF)'), ('ppt', 'Presentation (PPT)')], max_length=20),
        ),
    ]
