# Generated by Django 6.1.1 on 2026-09-11 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_chapterresource_resource_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('device_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_synced_manifest_version', models.IntegerField(default=0)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SyncManifestVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('manifest_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ContentAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=20)),
                ('filename', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=1000)),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('soft_deleted', 'Soft Deleted'), ('purged', 'Purged')], default='active', max_length=20)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deletion_reason', models.TextField(blank=True, default='')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_assets', to='api.chapter')),
                ('chapter_resource', models.OneToOneField(blank=True, help_text='Links to the existing ChapterResource record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_asset', to='api.chapterresource')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_assets', to='api.subject')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('remove', 'Remove'), ('restore', 'Restore'), ('hard_delete', 'Hard Delete')], max_length=20)),
                ('asset_filename', models.CharField(default='', max_length=500)),
                ('subject_name', models.CharField(default='', max_length=100)),
                ('chapter_title', models.CharField(default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('content_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='api.contentasset')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False, help_text='Admins can manage all subjects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_subjects', models.ManyToManyField(blank=True, related_name='assigned_teachers', to='api.subject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
