# Generated by Django 6.1 on 2026-09-11 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_chapterresource_resource_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_type", models.CharField(max_length=50)),
                ("text", models.TextField()),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_chunks",
                        to="api.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["chapter", "resource_type", "order"],
            },
        ),
    ]
