# Generated by Django 6.1 on 2026-09-11 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_contentchunk"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="hint_used",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ChapterQuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("options", models.JSONField(default=list)),
                ("correct_answer", models.CharField(max_length=255)),
                ("hint_text", models.TextField(blank=True)),
                (
                    "hint_review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("needs_rework", "Needs Rework"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_questions",
                        to="api.chapter",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="source_question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attempts",
                to="api.chapterquizquestion",
            ),
        ),
    ]
