# Generated by Django 5.1.15 on 2026-09-11 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_quizquestion_hint_used_chapterquizquestion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterFormulaSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='formula_sheet', to='api.chapter')),
            ],
        ),
    ]
