# Generated by Django 6.1.1 on 2026-09-11 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_devicesyncstatus_syncmanifestversion_contentasset_and_more'),
        ('api', '0008_quizquestion_hint_used_chapterquizquestion_and_more'),
    ]

    operations = [
    ]
