# Generated by Django 6.1 on 2026-09-12 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_chapterformulasheet"),
        ("api", "0009_merge_20260912_0504"),
    ]

    operations = []
